### ISSUE TITLE
Julia IR Support?

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/solidity#46]
I want to start a discussion between @theo25 and @axic about supporting the Julia IR for the compiler to IELE.

Right now the compiler is being modified to be able to emit IELE code directly from Solidity, but perhaps it makes more sense to emit IELE from Julia, and then have a separate step for lowering Solidity -> Julia.

@theo25 if the code for Solidity -> IELE has not gotten too far past the Julia fragment, do you think it's possible to "finish" the Solidity -> IELE compiler by actually finishing out the Solidity -> Julia compiler?

@axic how much work is needed here for Solidity -> Julia?

**Comment by dwightguth** [comment]
One question I would have before I can even know if that's possible is whether Julia assumes the existence of a stack or not.

**Comment by ehildenb** [comment]
Here is a link to the spec: http://solidity.readthedocs.io/en/develop/julia.html

**Comment by theo25** [comment]
Also I want to ask what features of Solidity get compiled away when it becomes Julia. I.e. does inheritance go away?

**Comment by ehildenb** [comment]
The reason I bring this up is because one of the goals of Julia is to offer a backend for eWASM as well, so that it servers as a nice mid-level language for blockchains. So it would make sense that we try to re-use it for IELE.

@dwightguth just glancing through the spec it looks like no assumption about stack.

@theo25 I'm not sure, maybe @axic  or @chriseth can clarify.

**Comment by chriseth** [comment]
We do not really know yet how much work `solidity -> iulia` will be, but we want to take the opportunity to correct some bad code in the meantime. iulia does not assume the existence of a stack, but it is nicely usable for stack-based virtual machines.

Iulia is just a thin wrapper around EVM bytecode, so it removes inheritance, types and many other things. It will hopefully retain internal functions (but it will add many more) and loops.

It will treat memory in the same way as the EVM treats memory. It might be that we have to change that in the future to allow for better analysis and optimizations.

**Comment by axic** [comment]
Oh, somehow I missed this issue going back years. Not sure how relevant this issue still is.

FYI the IR language was renamed to Yul, and as of Solidity 0.8.4 we have a pretty good feature coverage in our IR implementation. On the commandline it can be invoked via `--experimental-via-ir` to turn the entire pipeline to use it, or `--optimize --ir-optimized` can be used to access the generated Yul code.
