### ISSUE TITLE
Solidity feature: Function pointers

### ISSUE THREAD

**Issue by theo25** [runtimeverification/solidity#49]

**Comment by dwightguth** [comment]
It's worth asking whether we want to support function pointers via an encoding and a dispatch function or whether we want to add function pointers into iele itself. The latter might also make the plutus compiler easier to create.

**Comment by theo25** [comment]
If we add pointers of any type in iele, that will make the verification efforts significantly harder in my experience. Maybe it would be a good idea to discuss this at some point with people that work on evm verification.

**Comment by dwightguth** [comment]
I mean it wouldn't exactly be a pointer, more like a function signature (name and number of args) but I see your point. We should discuss this with Brandon and Daejun when the time comes.
