### ISSUE TITLE
Bugfixes (return statement + modifiers, inheritance etc.) 

### ISSUE THREAD

**Issue by dfilaretti** [runtimeverification/solidity#55]
Tests failing because of the interaction of return with modifiers:

* `function_modifier_local_variables`
* `function_modifier_multi_with_return`
* `function_modifier_multiple_times_local_vars`
* `return_does_not_skip_modifier`

Tests failing because of inheritance and the way we pass args to base constructors:

* `pass_dynamic_arguments_to_the_base`
* `pass_dynamic_arguments_to_the_base_base`
* `pass_dynamic_arguments_to_the_base_base_with_gap`

**Comment by dwightguth** [comment]
Fixed by #124 #113
